force-app/main/default/objects/Case/fields/Liner_brand__c.field-meta.xml
<CustomField>
    <fullName>Liner_brand__c</fullName>
    <label>Liner brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>Liquor</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Bread &amp; Bakery</fullName>
            </value>
            <value>
                <fullName>Fruit &amp; Vegetables</fullName>
            </value>
            <value>
                <fullName>Meat, Seafood &amp; Deli</fullName>
            </value>
            <value>
                <fullName>Dairy, Eggs and Meals</fullName>
            </value>
            <value>
                <fullName>Pantry</fullName>
            </value>
            <value>
                <fullName>Convenience Meals</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Drinks</fullName>
            </value>
            <value>
                <fullName>Liquor</fullName>
            </value>
            <value>
                <fullName>International Foods</fullName>
            </value>
            <value>
                <fullName>Healthy Living</fullName>
            </value>
            <value>
                <fullName>Household</fullName>
            </value>
            <value>
                <fullName>Health &amp; Beauty</fullName>
            </value>
            <value>
                <fullName>Baby</fullName>
            </value>
            <value>
                <fullName>Pet</fullName>
            </value>
            <value>
                <fullName>Tobacco</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Supermarkets</fullName>
            </value>
            <value>
                <fullName>Liquor Retail</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Australia</fullName>
                <default>true</default>
                <label>Australia</label>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>England</fullName>
            </value>
            <value>
                <fullName>Spain</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Liner_Brand__c.field-meta.xml
<CustomField>
    <fullName>Liner_Brand__c</fullName>
    <label>Liner Brand</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>Liquor</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Preferred_Notification_Channel__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Notification_Channel__c</fullName>
    <label>Preferred Notification Channel</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateCaseContactRecords.cls
public without sharing class CreateCaseContactRecords 
{

    @AuraEnabled
    public static void createCaseRecordOnSubmit(Contact conObj,Case caseObj, String fileName, String base64Data) 
    {
        string cFirstName = conObj.FirstName;
        String cLastName = conObj.LastName;
        String cEmail = conObj.Email;
        System.debug('contact => '+conObj);
        System.debug('contact FirstName=> '+conObj.FirstName);
        System.debug('contact LastName=> '+conObj.LastName);
        System.debug('contact LastName=> '+conObj.Email);

        System.debug('case => '+caseObj);
        System.debug('Case Subject=> '+caseObj.Subject);

       List<Contact> conList = [SELECT id from Contact where  FirstName = : cFirstName and LastName = :cLastName and Email = :cEmail LIMIT 1];
        Contact getConObj  = new Contact ();
        if( !conList.isEmpty())
        {
            getConObj = conList[0];
            System.debug('Existing Contact=' + getConObj);
           
        } 
        else
         {
             if( String.isNotBlank(conObj.FirstName) && String.isNotBlank(conObj.LastName) && String.isNotBlank(caseObj.Liner_brand__c))
             {
                getConObj.FirstName = conObj.FirstName;
                getConObj.LastName = conObj.LastName;
                getConObj.Email = conObj.Email;
                getConObj.Preferred_Notification_Channel__c = 'Email';
                getConObj.Country__c = 'Australia';
                getConObj.Brand__c = caseObj.Liner_brand__c;
                insert getConObj;
             }          
        
         }  
         if( getConObj != null)
         {
             Case newCaseObj = new Case();
             newCaseObj.Subject =caseObj.Subject;
             newCaseObj.Liner_brand__c = caseObj.Liner_brand__c;
             newCaseObj.Product__c = caseObj.Product__c;
             newCaseObj.Description = caseObj.Description;
             newCaseObj.ContactId = getConObj.id;
             insert newCaseObj;
             System.debug('Case created:'+newCaseObj.id);
             if(fileName!=null){
                System.debug('file Contents:'+base64Data);
                base64Data = EncodingUtil.urlDecode(base64Data, 'UTF-8');        
                ContentVersion v = new ContentVersion();
                v.versionData = EncodingUtil.base64Decode(base64Data);
                v.title = fileName;
                v.pathOnClient ='/'+fileName;
                v.FirstPublishLocationId = newCaseObj.id;
                insert v;
                System.debug('Content created:'+v.id);
             }            
         }  
        
    }
    
}