force-app/main/default/objects/Case/fields/Liner_brand__c.field-meta.xml
<CustomField>
    <fullName>Liner_brand__c</fullName>
    <label>Liner brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Retail</fullName>
                <default>true</default>
                <label>Retail</label>
            </value>
            <value>
                <fullName>Liquor</fullName>
            </value>
            <value>
                <fullName>Wholesale</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Time_remaining_to_close__c.field-meta.xml
<CustomField>
    <fullName>Time_remaining_to_close__c</fullName>
    <formula>TIMEVALUE(NOW())+1</formula>
    <label>Time remaining to close</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/gaugePageController.cls
public class gaugePageController {
    public String currentRecordId {get;set;}
    public String parameterValue {get;set;}
    public Case caseData{get;set;}
 
    public gaugePageController(ApexPages.StandardController controller) {
        currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
         caseData = [select Liner_brand__c ,	Priority, 	Time_remaining_to_close__c from Case where id =: currentRecordId ];
        parameterValue = ApexPages.CurrentPage().getparameters().get('nameParam');
    }
}